name: Build Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Decode signing key
      run: echo "$SIGNING_KEY" | base64 -d > release-key.jks
      env:
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Build signed APK
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: BluetoothJammer-release
        path: app/build/outputs/apk/release/app-release.apk
